version: '3.8'
services:
    spotify-readme:
        env_file:
            - .env
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./api:/api
    redis:
        image: redis:latest
        container_name: redis-serverless
        ports:
            - "6379:6379"
volumes:
  persistent:
